# This is a alternativ gnu make file to cmake


all:
	g++ -o ./src/main.o -I/usr/local/include/ -L/usr/local/lib/nltemplate/ -c ./src/main.cpp
	g++ -o example -I/usr/local/include/ -L/usr/local/lib/nltemplate/ -lnlpemplate ./src/main.o
